# Generated by Django 4.2.4 on 2023-10-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, default='coding', related_name='posts', to='blog.category'),
        ),
    ]
