# Generated by Django 4.2.4 on 2023-09-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_author_comment_user_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=20000000),
        ),
    ]
